name: tasks
on:
  workflow_dispatch:
  schedule:
    - cron: '12 4 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - name: 'setup timezone'
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: 'setup python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'install requirements'
        run: pip install -r requirements.txt
      - name: 'working'
        env:
          SMTP: ${{ secrets.SMTP }}
          TASKS: ${{ secrets.TASKS }}
        run: |
          python main.py >> ./run.log
          tail run.log
      - name: 'auto commit'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'auto tasks'
          branch: main